spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/vaultdrive
spring.datasource.username=${DB_USERNAME:vaultdrive}
spring.datasource.password=${DB_PASSWORD}

# Flyway
spring.flyway.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# JWT configuration
vaultdrive.jwt.secret=${JWT_SECRET}
vaultdrive.jwt.issuer=https://vaultdrive.local
vaultdrive.jwt.access-token-minutes=15